name: Deploy to STRAP
run-name: Deploy app to STRAP
on:
  push:
    branches:
      - staging
jobs:
  Deploy-to-STRAP:
    runs-on: ubuntu-latest
    env:
      REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - name: Clone deploy repo from ARCsoft's Gitlab
        run: |
          git clone https://gitlab.com/uvic-arcsoft/misc/community-energy-finance-explorer.git app
          cd app
          make install-update-submodules
          cd community_energy_finance_explorer
          git checkout staging
          cd ..

      - name: Generate TAG
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          DATE=$(date +'%Y%m%d')
          echo "TAG=${GITHUB_REF_NAME}-${SHORT_SHA}-${DATE}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1
          IMAGE_NAME=${REGISTRY_HOST}/community-energy/app:${TAG}
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          docker build --platform linux/amd64 -t ${IMAGE_NAME} .

      - name: Push Docker image
        run: |
          echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY_HOST} -u "${REGISTRY_USER}" -p
          docker push ${IMAGE_NAME}
