name: Deploy to STRAP
run-name: Deploy app to STRAP
on:
  push:
    branches:
      - staging
jobs:
  Deploy-to-STRAP:
    runs-on: ubuntu-latest
    steps:
      - name: Clone deploy repo from ARCsoft's Gitlab
        run: |
          git clone https://gitlab.com/uvic-arcsoft/misc/community-energy-finance-explorer.git app
          cd app
          make install-update-submodules
          cd community_energy_finance_explorer
          git checkout staging
          cd ..

      - name: Generate TAG
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          DATE=$(date +'%Y%m%d')
          echo "TAG=${GITHUB_REF_NAME}-${SHORT_SHA}-${DATE}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          export DOCKER_BUILDKIT=1
          echo "IMAGE_NAME=${REGISTRY_HOST}/community-energy/app:${TAG}"
          docker build --platform linux/amd64 -t ${IMAGE_NAME}

      - name: Push Docker image
        run: |
          docker login ${REGISTRY_HOST} -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}"
          docker push ${IMAGE_NAME}
