name: Deploy to STRAP
run-name: Deploy app to STRAP
on:
  push:
    branches:
      - staging
jobs:
  Deploy-to-STRAP:
    runs-on: ubuntu-latest
    steps:
      - name: Clone deploy repo from ARCsoft's Gitlab
        run: |
          git clone https://gitlab.com/uvic-arcsoft/misc/community-energy-finance-explorer.git app
          cd app
          make install-update-submodules
          cd community-energy-finance-explorer
          git checkout staging
          cd ..

      - name: Generate TAG
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          DATE=$(date +'%Y%m%d')
          echo "TAG=${GITHUB_REF_NAME}-${SHORT_SHA}-${DATE}" >> $GITHUB_ENV

      - name: Show TAG
        run: echo "TAG is $TAG"
